export type { IconWrapperProps } from './icon';
export { CheckIcon } from './check';
export { PrevIcon } from "./prev";
export { PlusIcon } from "./plus";
export { CoinIcon } from "./coin";
export { MirrorIcon } from "./mirror";
export { WheelIcon } from "./wheel";
export { ChestIcon } from "./chest";
export { BookIcon } from "./book";
export { NewsIcon } from "./news";